// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIFyIfozUBDDfZVIoXbuTdd6zMhlhpZsk',
    appId: '1:259052883784:web:8c806353cc7b34921ead7d',
    messagingSenderId: '259052883784',
    projectId: 'tutortyper-b2e13',
    authDomain: 'tutortyper-b2e13.firebaseapp.com',
    storageBucket: 'tutortyper-b2e13.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdY0bDF1p50VAFuQRV3I5-WE257OscwEE',
    appId: '1:259052883784:android:6ec5084e110f37801ead7d',
    messagingSenderId: '259052883784',
    projectId: 'tutortyper-b2e13',
    storageBucket: 'tutortyper-b2e13.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiJGairQTNJFHqrnF0MLjlb7yZjoqpQKA',
    appId: '1:259052883784:ios:e10457927d87b8b61ead7d',
    messagingSenderId: '259052883784',
    projectId: 'tutortyper-b2e13',
    storageBucket: 'tutortyper-b2e13.firebasestorage.app',
    iosBundleId: 'com.TutorTyper.tutortyperApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiJGairQTNJFHqrnF0MLjlb7yZjoqpQKA',
    appId: '1:259052883784:ios:e10457927d87b8b61ead7d',
    messagingSenderId: '259052883784',
    projectId: 'tutortyper-b2e13',
    storageBucket: 'tutortyper-b2e13.firebasestorage.app',
    iosBundleId: 'com.TutorTyper.tutortyperApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIFyIfozUBDDfZVIoXbuTdd6zMhlhpZsk',
    appId: '1:259052883784:web:88ef551b86af5ecc1ead7d',
    messagingSenderId: '259052883784',
    projectId: 'tutortyper-b2e13',
    authDomain: 'tutortyper-b2e13.firebaseapp.com',
    storageBucket: 'tutortyper-b2e13.firebasestorage.app',
  );
}
